using System.Text.RegularExpressions;

namespace Microsoft.PWABuilder.Common;

/// <summary>
/// Provides the JavaScript and CSS entry point for the app generated by Vite during production builds.
/// </summary>
public class ViteEntryPointProvider
{
    public ViteEntryPointProvider(IWebHostEnvironment env)
    {
        // If we're in development, production entry point isn't used.
        if (env.IsDevelopment())
        {
            EntryPointJs = string.Empty;
            EntryPointCss = string.Empty;
        }
        else
        {
            var (jsPath, cssPath) = GetEntryPointJsFromIndex(env);
            EntryPointJs = jsPath;
            EntryPointCss = cssPath;
        }
    }

    /// <summary>
    /// Gets the JavaScript entry point for app.
    /// </summary>
    public string EntryPointJs { get; init; }

    /// <summary>
    /// Gets the CSS to load during app initialization.
    /// </summary>
    public string EntryPointCss { get; init; }

    private static (string jsPath, string cssPath) GetEntryPointJsFromIndex(IWebHostEnvironment env)
    {
        var indexHtmlPath = Path.Combine(env.WebRootPath, "vite-index.html");
        if (!File.Exists(indexHtmlPath))
        {
            throw new FileNotFoundException(
                $"Unable to find vite-index.html at {indexHtmlPath}. This means the JS entry point for the app won't be found."
            );
        }

        var fileContents = File.ReadAllText(indexHtmlPath);

        // Look for the <script type="module" src="/assets/js/whatever.js"> tag.
        var srcRegex = new Regex(
            "<script\\s+[^>]+src=['|\"]([^\"']+)['|\"]",
            RegexOptions.IgnoreCase
        );
        var jsRegexResult = srcRegex.Match(fileContents);
        if (!jsRegexResult.Success || jsRegexResult.Groups.Count < 2)
        {
            throw new InvalidOperationException(
                $"Unable to find the JavaScript entry point in {indexHtmlPath}. Has the format of the file been changed?"
            );
        }

        var jsPath = jsRegexResult.Groups[1].Value;

        // Match the bundled stylesheet link, tolerating any additional attributes
        // between rel="stylesheet" and href (e.g. the `crossorigin` attribute Vite
        // emits). A stricter regex that required href immediately after rel silently
        // failed once Vite started adding crossorigin, leaving EntryPointCss empty and
        // shipping the app with no Web Awesome theme tokens (transparent form controls).
        var cssRegex = new Regex(
            "<link\\s+[^>]*?rel=['\"]stylesheet['\"][^>]*?href=['\"](/code/index-[a-zA-Z0-9_-]+\\.css)['\"]",
            RegexOptions.IgnoreCase
        );
        var cssRegexResult = cssRegex.Match(fileContents);
        if (!cssRegexResult.Success)
        {
            throw new InvalidOperationException(
                $"Unable to find the CSS entry point in {indexHtmlPath}. Has the format of the file been changed?"
            );
        }

        var cssPath = cssRegexResult.Groups[1].Value;
        return (jsPath, cssPath);
    }
}
