id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - daily:
          time: 7:0
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'needs author feedback :memo:'
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      actions:
      - addLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      - addReply:
          reply: This issue has been automatically marked as "no-recent-activity" because it requires author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs within **7 days** of this comment.
    - description: 
      frequencies:
      - daily:
          time: 7:0
      filters:
      - isOpen
      - hasLabel:
          label: 'needs author feedback :memo:'
      - hasLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      - noActivitySince:
          days: 7
      - isIssue
      actions:
      - addReply:
          reply: This issue has been automatically closed because it was marked as requiring author feedback but has not had any activity for **7 days**.
      - closeIssue
    - description: 
      frequencies:
      - daily:
          time: 7:0
      filters:
      - isOpen
      - isIssue
      - hasLabel:
          label: 'needs triage :mag:'
      - noActivitySince:
          days: 7
      actions:
      - addLabel:
          label: 'needs attention :wave:'
      - addReply:
          reply: "This issue has been marked as \"needs attention \U0001F44B\" since it has not been triaged for **7 days**.  Please triage the issue ."
    - description: 
      frequencies:
      - daily:
          time: 7:0
      filters:
      - isPullRequest
      - isOpen
      - hasLabel:
          label: 'needs author feedback :memo:'
      - hasLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      - noActivitySince:
          days: 30
      actions:
      - closeIssue
    - description: 
      frequencies:
      - daily:
          time: 7:0
      filters:
      - isPullRequest
      - isOpen
      - hasLabel:
          label: 'needs author feedback :memo:'
      - noActivitySince:
          days: 15
      - isNotLabeledWith:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      actions:
      - addLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      - addReply:
          reply: This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **15 days**. It will be closed if no further activity occurs **within 30 days of this comment**.
    eventResponderTasks:
    - if:
      - payloadType: Issues
      - hasLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      - isAction:
          action: Edited
      then:
      - removeLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      - addReply:
          reply: 'Glad to have you back! I have removed the "no-recent-activity" label due to the occurrence of an activity. '
      description: 
    - if:
      - payloadType: Issue_Comment
      - isOpen
      - hasLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      then:
      - removeLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      description: 
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'needs author feedback :memo:'
      - isOpen
      then:
      - addLabel:
          label: 'needs attention :wave:'
      - removeLabel:
          label: 'needs author feedback :memo:'
      description: 
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      then:
      - addReply:
          reply: "Thanks ${issueAuthor} for opening a Pull Request! The reviewers will test the PR and highlight if there is any conflict or changes required. If the PR is approved we will proceed to merge the pull request \U0001F64C"
      description: 
    - if:
      - payloadType: Pull_Request_Review
      - isAction:
          action: Submitted
      - isReviewState:
          reviewState: Changes_requested
      then:
      - addLabel:
          label: 'needs author feedback :memo:'
      description: 
    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          issueAuthor: True
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'needs author feedback :memo:'
      then:
      - removeLabel:
          label: 'needs author feedback :memo:'
      description: 
    - if:
      - payloadType: Issue_Comment
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'needs author feedback :memo:'
      then:
      - removeLabel:
          label: 'needs author feedback :memo:'
      description: 
    - if:
      - payloadType: Pull_Request_Review
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'needs author feedback :memo:'
      then:
      - removeLabel:
          label: 'needs author feedback :memo:'
      description: 
    - if:
      - payloadType: Pull_Request
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      then:
      - removeLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      description: 
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      then:
      - removeLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      description: 
    - if:
      - payloadType: Pull_Request_Review
      - hasLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      then:
      - removeLabel:
          label: 'no-recent-activity :chart_with_downwards_trend:'
      description: 
    - if:
      - payloadType: Issue_Comment
      then:
      - cleanEmailReply
      description: 
onFailure: 
onSuccess: 
