import { LitElement, TemplateResult } from 'lit';
import { Manifest } from '@pwabuilder/manifest-validation';
import '../components/app-header';
import '../components/todo-list-item';
import '../components/manifest-editor-frame';
import '../components/publish-pane';
import '../components/test-publish-pane';
import '../components/sw-selector';
import '../components/share-card';
import '../components/manifest-info-card';
import '../components/sw-info-card';
import '../components/arrow-link';
import '@shoelace-style/shoelace/dist/components/button/button.js';
import '@shoelace-style/shoelace/dist/components/button-group/button-group.js';
import '@shoelace-style/shoelace/dist/components/skeleton/skeleton.js';
import '@shoelace-style/shoelace/dist/components/tooltip/tooltip.js';
import '@shoelace-style/shoelace/dist/components/icon/icon.js';
import '@shoelace-style/shoelace/dist/components/details/details.js';
import '@shoelace-style/shoelace/dist/components/dialog/dialog.js';
import '@shoelace-style/shoelace/dist/components/progress-ring/progress-ring.js';
import '@shoelace-style/shoelace/dist/components/spinner/spinner.js';
import '@shoelace-style/shoelace/dist/components/textarea/textarea.js';
import '@shoelace-style/shoelace/dist/components/copy-button/copy-button.js';
import '@shoelace-style/shoelace/dist/components/dropdown/dropdown.js';
import SlDropdown from '@shoelace-style/shoelace/dist/components/dropdown/dropdown.js';
import { Icon, ManifestContext } from '../utils/interfaces';
import { Analysis, PwaCapability, PwaCapabilityLevel } from './app-report.api';
export declare class AppReport extends LitElement {
    siteUrl: string;
    errorMessage: string | undefined;
    isAppCardInfoLoading: boolean;
    runningTests: boolean;
    analysisId: string | null;
    analysis: Analysis | null;
    lastTested: string;
    startingManifestEditorTab: string;
    focusOnME: string;
    proxyLoadingImage: boolean;
    showIconsErrorBanner: boolean;
    showRetestConfirmationModal: boolean;
    thingToAdd: string;
    retestConfirmed: boolean;
    readDenied: boolean;
    createdManifest: boolean;
    manifestContext: ManifestContext | undefined;
    todoFilters: PwaCapabilityLevel[];
    openTooltips: SlDropdown[];
    stopShowingNotificationTooltip: boolean;
    closeOpenTooltips: boolean;
    darkMode: boolean;
    appCard: {
        siteName: string;
        description: string;
        siteUrl: string;
        iconURL: string;
        iconAlt: string;
    };
    analysisStatusCheckHandle: number;
    readonly analysisStatusCheckInterval = 2000;
    readonly CardStyles: {
        backgroundColor: string;
        color: string;
    };
    readonly BorderStyles: {
        borderTop: string;
    };
    readonly LastEditedStyles: {
        color: string;
    };
    static styles: import("lit").CSSResult[];
    connectedCallback(): Promise<void>;
    disconnectedCallback(): void;
    pollLastTested(): void;
    populateAppCard(manifestContext: ManifestContext, url?: string): Promise<void>;
    createMissingAppCard(url: string): {
        siteName: string;
        siteUrl: string;
        description: string;
        iconURL: string;
        iconAlt: string;
    };
    testImage(url: string): Promise<unknown>;
    pickTextColorBasedOnBgColorAdvanced(bgColor: string, lightColor: string, darkColor: string): string;
    private applyManifestContext;
    processManifest(appUrl: string, manifestUrl?: string, manifestContents?: string): Promise<ManifestContext>;
    private checkAnalysisStatus;
    analysisCompleted(): void;
    analysisFailed(): void;
    analysisUpdated(analysis: Analysis): Promise<void>;
    runAllTests(url: string, retryOnFailure?: boolean): Promise<void>;
    /**
    * Triggers all tests to retest
    * If coming from confirmation is true, we have to delay a bit so a special message can show
    * @param {boolean} comingFromConfirmation
    * @return {void}
    */
    retest(comingFromConfirmation: boolean): Promise<void>;
    delay(ms: number): Promise<unknown>;
    resetData(): void;
    openShareCardModal(): Promise<void>;
    openManifestEditorModal(focusOn?: string, tab?: string): Promise<void | undefined>;
    openSWSelectorModal(): Promise<void>;
    openPublishModal(): Promise<void>;
    openTestPublishModal(): Promise<void>;
    iconSrcListParse(icon: any): string;
    handleImageUrl(icon: Icon, manifest: Manifest, manifestURL: string): string | undefined;
    decideColor(card: string): {
        green: boolean;
        red: boolean;
        yellow: boolean;
    };
    getRingColor(card: string): string | undefined;
    decideMessage(valid: number, total: number, card: string): string;
    animateItem(e: CustomEvent): Promise<void>;
    rotateZero(card: string, e?: Event): void;
    rotateNinety(card: string, e?: Event, init?: boolean): void;
    renderTodoFilters(): TemplateResult;
    renderTodoFilterBtn(level: PwaCapabilityLevel, count: number): TemplateResult<1>;
    handleShowingTooltip(e: CustomEvent, origin: string, field: string): void;
    closeTooltipOnScroll(): void;
    renderReadDialog(): TemplateResult;
    renderAppCardInfo(): TemplateResult;
    renderShareButton(btnId: string): TemplateResult;
    renderAppCardFooter(): TemplateResult;
    renderPackageForStores(): TemplateResult;
    private renderIconErrorBanner;
    private renderTodoTooltip;
    private renderTodos;
    private renderManifestSection;
    renderManifestDetails(): TemplateResult;
    renderManifestDetailsChecklist(): TemplateResult;
    private renderManifestValidations;
    private renderManifestFieldCheck;
    private renderEditManifestButton;
    private renderManifestScore;
    private renderManifestScoreRing;
    private renderFilteredTodoItems;
    private renderTodo;
    private getThemedIcon;
    render(): TemplateResult;
    renderShareScore(): TemplateResult;
    renderServiceWorkerFeaturesSection(): TemplateResult;
    renderServiceWorkerFeaturesHeader(): TemplateResult;
    renderServiceWorkerFeaturesRing(): TemplateResult;
    renderServiceWorkerCapabilities(): TemplateResult;
    renderServiceWorkerActions(): TemplateResult;
    renderServiceWorkerCapability(capability: PwaCapability): TemplateResult;
    renderAppCapabilitiesSection(): TemplateResult;
    renderAppCapabilitiesHeader(): TemplateResult;
    renderAppCapabilitiesRing(): TemplateResult;
    renderAppCapabilitiesCards(): TemplateResult;
    renderAppCapabilityCard(v: PwaCapability): TemplateResult;
    renderPackageSpinner(): TemplateResult;
    renderManifestEditorDialog(): TemplateResult;
    renderAnalysisInfoDialog(): TemplateResult;
    renderAnalysisErrorDialog(): TemplateResult;
    showAnalysisErrorDialog(): void;
    toggleTodoFilter(level: PwaCapabilityLevel): void;
    showAnalysisLog(): void;
    sortActionItems(a: PwaCapability, b: PwaCapability): number;
}
