import { LitElement, TemplateResult } from "lit";
import "../components/app-header";
import "../components/app-file-input";
import { FileInputDetails, Lazy } from "../utils/interfaces";
import "@shoelace-style/shoelace/dist/components/button/button.js";
type ColorRadioValues = "best guess" | "transparent" | "custom";
export declare class ImageGenerator extends LitElement {
    platformSelected: Array<boolean>;
    files: Lazy<FileList>;
    padding: number;
    colorOption: ColorRadioValues;
    color: string;
    selectAllState: boolean;
    generating: boolean;
    generateEnabled: boolean;
    error: Lazy<string>;
    static get styles(): import("lit").CSSResult[];
    constructor();
    firstUpdated(): void;
    render(): TemplateResult<1>;
    renderPlatformList(): TemplateResult<1>[];
    renderColorPicker(): TemplateResult<1> | undefined;
    renderError(): TemplateResult;
    handleInputChange(event: CustomEvent<FileInputDetails>): void;
    handlePaddingChange(event: Event): void;
    handleCheckbox(event: Event): void;
    handleBackgroundRadioChange(event: CustomEvent): void;
    handleThemeColorInputChange(event: Event): void;
    generateZip(): Promise<void>;
    downloadZip(zipUrl: string, fileName: string): void;
    checkGenerateEnabled(): boolean;
}
export {};
