namespace PWABuilder.Validations.Models
{
    public class Language
    {
        public required string Code { get; set; }
        public required string Name { get; set; }
    }

    public static class Languages
    {
        public static List<Language> GetLanguages()
        {
            return
            [
                new() { Code = "ab", Name = "Abkhaz" },
                new() { Code = "aa", Name = "Afar" },
                new() { Code = "af", Name = "Afrikaans" },
                new() { Code = "ak", Name = "Akan" },
                new() { Code = "sq", Name = "Albanian" },
                new() { Code = "am", Name = "Amharic" },
                new() { Code = "ar", Name = "Arabic" },
                new() { Code = "an", Name = "Aragonese" },
                new() { Code = "hy", Name = "Armenian" },
                new() { Code = "as", Name = "Assamese" },
                new() { Code = "av", Name = "Avaric" },
                new() { Code = "ae", Name = "Avestan" },
                new() { Code = "ay", Name = "Aymara" },
                new() { Code = "az", Name = "Azerbaijani" },
                new() { Code = "bm", Name = "Bambara" },
                new() { Code = "ba", Name = "Bashkir" },
                new() { Code = "eu", Name = "Basque" },
                new() { Code = "be", Name = "Belarusian" },
                new() { Code = "bn", Name = "Bengali" },
                new() { Code = "bh", Name = "Bihari" },
                new() { Code = "bi", Name = "Bislama" },
                new() { Code = "bs", Name = "Bosnian" },
                new() { Code = "br", Name = "Breton" },
                new() { Code = "bg", Name = "Bulgarian" },
                new() { Code = "my", Name = "Burmese" },
                new() { Code = "ca", Name = "Catalan; Valencian" },
                new() { Code = "ch", Name = "Chamorro" },
                new() { Code = "ce", Name = "Chechen" },
                new() { Code = "ny", Name = "Chichewa; Chewa; Nyanja" },
                new() { Code = "zh", Name = "Chinese" },
                new() { Code = "cv", Name = "Chuvash" },
                new() { Code = "kw", Name = "Cornish" },
                new() { Code = "co", Name = "Corsican" },
                new() { Code = "cr", Name = "Cree" },
                new() { Code = "hr", Name = "Croatian" },
                new() { Code = "cs", Name = "Czech" },
                new() { Code = "da", Name = "Danish" },
                new() { Code = "dv", Name = "Divehi; Dhivehi; Maldivian;" },
                new() { Code = "nl", Name = "Dutch" },
                new() { Code = "en", Name = "English" },
                new() { Code = "eo", Name = "Esperanto" },
                new() { Code = "et", Name = "Estonian" },
                new() { Code = "ee", Name = "Ewe" },
                new() { Code = "fo", Name = "Faroese" },
                new() { Code = "fj", Name = "Fijian" },
                new() { Code = "fi", Name = "Finnish" },
                new() { Code = "fr", Name = "French" },
                new() { Code = "ff", Name = "Fula; Fulah; Pulaar; Pular" },
                new() { Code = "gl", Name = "Galician" },
                new() { Code = "ka", Name = "Georgian" },
                new() { Code = "de", Name = "German" },
                new() { Code = "el", Name = "Greek, Modern" },
                new() { Code = "gn", Name = "Guaraní" },
                new() { Code = "gu", Name = "Gujarati" },
                new() { Code = "ht", Name = "Haitian; Haitian Creole" },
                new() { Code = "ha", Name = "Hausa" },
                new() { Code = "he", Name = "Hebrew (modern)" },
                new() { Code = "hz", Name = "Herero" },
                new() { Code = "hi", Name = "Hindi" },
                new() { Code = "ho", Name = "Hiri Motu" },
                new() { Code = "hu", Name = "Hungarian" },
                new() { Code = "ia", Name = "Interlingua" },
                new() { Code = "id", Name = "Indonesian" },
                new() { Code = "ie", Name = "Interlingue" },
                new() { Code = "ga", Name = "Irish" },
                new() { Code = "ig", Name = "Igbo" },
                new() { Code = "ik", Name = "Inupiaq" },
                new() { Code = "io", Name = "Ido" },
                new() { Code = "is", Name = "Icelandic" },
                new() { Code = "it", Name = "Italian" },
                new() { Code = "iu", Name = "Inuktitut" },
                new() { Code = "ja", Name = "Japanese" },
                new() { Code = "jv", Name = "Javanese" },
                new() { Code = "kl", Name = "Kalaallisut, Greenlandic" },
                new() { Code = "kn", Name = "Kannada" },
                new() { Code = "kr", Name = "Kanuri" },
                new() { Code = "ks", Name = "Kashmiri" },
                new() { Code = "kk", Name = "Kazakh" },
                new() { Code = "km", Name = "Khmer" },
                new() { Code = "ki", Name = "Kikuyu, Gikuyu" },
                new() { Code = "rw", Name = "Kinyarwanda" },
                new() { Code = "ky", Name = "Kirghiz, Kyrgyz" },
                new() { Code = "kv", Name = "Komi" },
                new() { Code = "kg", Name = "Kongo" },
                new() { Code = "ko", Name = "Korean" },
                new() { Code = "ku", Name = "Kurdish" },
                new() { Code = "kj", Name = "Kwanyama, Kuanyama" },
                new() { Code = "la", Name = "Latin" },
                new() { Code = "lb", Name = "Luxembourgish, Letzeburgesch" },
                new() { Code = "lg", Name = "Luganda" },
                new() { Code = "li", Name = "Limburgish, Limburgan, Limburger" },
                new() { Code = "ln", Name = "Lingala" },
                new() { Code = "lo", Name = "Lao" },
                new() { Code = "lt", Name = "Lithuanian" },
                new() { Code = "lu", Name = "Luba-Katanga" },
                new() { Code = "lv", Name = "Latvian" },
                new() { Code = "gv", Name = "Manx" },
                new() { Code = "mk", Name = "Macedonian" },
                new() { Code = "mg", Name = "Malagasy" },
                new() { Code = "ms", Name = "Malay" },
                new() { Code = "ml", Name = "Malayalam" },
                new() { Code = "mt", Name = "Maltese" },
                new() { Code = "mi", Name = "Māori" },
                new() { Code = "mr", Name = "Marathi (Marāṭhī)" },
                new() { Code = "mh", Name = "Marshallese" },
                new() { Code = "mn", Name = "Mongolian" },
                new() { Code = "na", Name = "Nauru" },
                new() { Code = "nv", Name = "Navajo, Navaho" },
                new() { Code = "nb", Name = "Norwegian Bokmål" },
                new() { Code = "nd", Name = "North Ndebele" },
                new() { Code = "ne", Name = "Nepali" },
                new() { Code = "ng", Name = "Ndonga" },
                new() { Code = "nn", Name = "Norwegian Nynorsk" },
                new() { Code = "no", Name = "Norwegian" },
                new() { Code = "ii", Name = "Nuosu" },
                new() { Code = "nr", Name = "South Ndebele" },
                new() { Code = "oc", Name = "Occitan" },
                new() { Code = "oj", Name = "Ojibwe, Ojibwa" },
                new()
                {
                    Code = "cu",
                    Name =
                        "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
                },
                new() { Code = "om", Name = "Oromo" },
                new() { Code = "or", Name = "Oriya" },
                new() { Code = "os", Name = "Ossetian, Ossetic" },
                new() { Code = "pa", Name = "Panjabi, Punjabi" },
                new() { Code = "pi", Name = "Pāli" },
                new() { Code = "fa", Name = "Persian" },
                new() { Code = "pl", Name = "Polish" },
                new() { Code = "ps", Name = "Pashto, Pushto" },
                new() { Code = "pt", Name = "Portuguese" },
                new() { Code = "qu", Name = "Quechua" },
                new() { Code = "rm", Name = "Romansh" },
                new() { Code = "rn", Name = "Kirundi" },
                new() { Code = "ro", Name = "Romanian, Moldavian, Moldovan" },
                new() { Code = "ru", Name = "Russian" },
                new() { Code = "sa", Name = "Sanskrit (Saṁskṛta)" },
                new() { Code = "sc", Name = "Sardinian" },
                new() { Code = "sd", Name = "Sindhi" },
                new() { Code = "se", Name = "Northern Sami" },
                new() { Code = "sm", Name = "Samoan" },
                new() { Code = "sg", Name = "Sango" },
                new() { Code = "sr", Name = "Serbian" },
                new() { Code = "gd", Name = "Scottish Gaelic; Gaelic" },
                new() { Code = "sn", Name = "Shona" },
                new() { Code = "si", Name = "Sinhala, Sinhalese" },
                new() { Code = "sk", Name = "Slovak" },
                new() { Code = "sl", Name = "Slovene" },
                new() { Code = "so", Name = "Somali" },
                new() { Code = "st", Name = "Southern Sotho" },
                new() { Code = "es", Name = "Spanish; Castilian" },
                new() { Code = "su", Name = "Sundanese" },
                new() { Code = "sw", Name = "Swahili" },
                new() { Code = "ss", Name = "Swati" },
                new() { Code = "sv", Name = "Swedish" },
                new() { Code = "ta", Name = "Tamil" },
                new() { Code = "te", Name = "Telugu" },
                new() { Code = "tg", Name = "Tajik" },
                new() { Code = "th", Name = "Thai" },
                new() { Code = "ti", Name = "Tigrinya" },
                new() { Code = "bo", Name = "Tibetan Standard, Tibetan, Central" },
                new() { Code = "tk", Name = "Turkmen" },
                new() { Code = "tl", Name = "Tagalog" },
                new() { Code = "tn", Name = "Tswana" },
                new() { Code = "to", Name = "Tonga (Tonga Islands)" },
                new() { Code = "tr", Name = "Turkish" },
                new() { Code = "ts", Name = "Tsonga" },
                new() { Code = "tt", Name = "Tatar" },
                new() { Code = "tw", Name = "Twi" },
                new() { Code = "ty", Name = "Tahitian" },
                new() { Code = "ug", Name = "Uighur, Uyghur" },
                new() { Code = "uk", Name = "Ukrainian" },
                new() { Code = "ur", Name = "Urdu" },
                new() { Code = "uz", Name = "Uzbek" },
                new() { Code = "ve", Name = "Venda" },
                new() { Code = "vi", Name = "Vietnamese" },
                new() { Code = "vo", Name = "Volapük" },
                new() { Code = "wa", Name = "Walloon" },
                new() { Code = "cy", Name = "Welsh" },
                new() { Code = "wo", Name = "Wolof" },
                new() { Code = "fy", Name = "Western Frisian" },
                new() { Code = "xh", Name = "Xhosa" },
                new() { Code = "yi", Name = "Yiddish" },
                new() { Code = "yo", Name = "Yoruba" },
                new() { Code = "za", Name = "Zhuang, Chuang" },
                // Add more languages as needed
            ];
        }

        public static bool IsValidLanguageCode(string code)
        {
            var langUsed = code.Contains("-") ? code.Trim().Split("-")[0] : code.Trim();
            return GetLanguages()
                .Any(lang => lang.Code.Equals(langUsed, StringComparison.OrdinalIgnoreCase));
        }
    }
}
