import { Manifest, FilesParams } from '@pwabuilder/manifest-validation';
import { LitElement, PropertyValueMap } from 'lit';
import "./manifest-field-tooltip";
import "./search-extensions";
import '@shoelace-style/shoelace/dist/components/input/input.js';
import '@shoelace-style/shoelace/dist/components/select/select.js';
import '@shoelace-style/shoelace/dist/components/button/button.js';
import '@shoelace-style/shoelace/dist/components/option/option.js';
export declare class ManifestShareForm extends LitElement {
    manifest: Manifest;
    manifestURL: string;
    focusOn: string;
    addingTarget: boolean;
    removeClicked: boolean;
    postSelected: boolean;
    files: any;
    numOfFiles: number;
    filteredList: string[];
    confirmRemove: boolean;
    private shouldValidateAllFields;
    private validationPromise;
    private errorCount;
    private fileError;
    static get styles(): import("lit").CSSResult;
    constructor();
    protected updated(_changedProperties: PropertyValueMap<any> | Map<PropertyKey, unknown>): Promise<void>;
    handleErrorCount(): void;
    private requestValidateAllFields;
    validateAllFields(): Promise<void>;
    protected firstUpdated(_changedProperties: PropertyValueMap<any> | Map<PropertyKey, unknown>): void;
    decideFocus(field: string): {
        focus: boolean;
    };
    toggleForm(adding: boolean): void;
    handleMethodChange(): void;
    composeFiles(data: FilesParams[]): void;
    handleFileError(e: CustomEvent): void;
    parameterErrors(addingErrors: boolean): void;
    areParamsEmpty(param_inputs: NodeList): boolean;
    pushEmptyFile(): void;
    removeFile(e: CustomEvent): void;
    renderFiles(): any;
    handleTopLevelInputChange(field: string): Promise<void>;
    handleParameterInputChange(field: string): Promise<void>;
    handleFileChange(e: CustomEvent): Promise<void>;
    renderAddorRemove(): import("lit-html").TemplateResult<1>;
    goBackToAdding(): void;
    removeShareTarget(): void;
    render(): import("lit-html").TemplateResult<1>;
}
