import customSettings from "./custom-settings.js";

const lighthouseSettings = {
  extends: "lighthouse:default",
  settings: { ...customSettings },
  artifacts: [
    { id: "DevtoolsLog", gatherer: "devtools-log" },
    { id: "InstallabilityErrors", gatherer: "installability-errors" },
    { id: "InspectorIssues", gatherer: "inspector-issues" },
    {
      id: "ServiceWorkerGatherer",
      gatherer: "custom-audits/service-worker/service-worker-gatherer",
    },
    { id: "WebAppManifest", gatherer: "web-app-manifest" },
    {
      id: "OfflineGatherer",
      gatherer: "custom-audits/offline/offline-gatherer",
    },
    { id: "devtoolsLogs", gatherer: "devtools-log-compat" },
  ],

  audits: [
    "is-on-https",
    "custom-audits/service-worker/service-worker-audit",
    "custom-audits/offline/offline-audit",
    "custom-audits/https/https-audit",
    "viewport",
    "metrics/first-contentful-paint",
    "metrics/largest-contentful-paint",
    "metrics/first-meaningful-paint",
    "metrics/speed-index",
    "screenshot-thumbnails",
    "final-screenshot",
    "metrics/total-blocking-time",
    "metrics/max-potential-fid",
    "metrics/cumulative-layout-shift",
    "metrics/interaction-to-next-paint",
    "errors-in-console",
    "server-response-time",
    "metrics/interactive",
    "user-timings",
    "critical-request-chains",
    "redirects",
    "installable-manifest",
    "splash-screen",
    "themed-omnibox",
    "maskable-icon",
    "content-width",
    "image-aspect-ratio",
    "image-size-responsive",
    "preload-fonts",
    "deprecations",
    "mainthread-work-breakdown",
    "bootup-time",
    "uses-rel-preload",
    "uses-rel-preconnect",
    "font-display",
    "diagnostics",
    "network-requests",
    "network-rtt",
    "network-server-latency",
    "main-thread-tasks",
    "metrics",
    "performance-budget",
    "timing-budget",
    "third-party-summary",
    "third-party-facades",
    "largest-contentful-paint-element",
    "lcp-lazy-loaded",
    "layout-shift-elements",
    "long-tasks",
    "no-unload-listeners",
    "non-composited-animations",
    "unsized-images",
    "valid-source-maps",
    "prioritize-lcp-image",
    "csp-xss",
    "script-treemap-data",
    "manual/pwa-cross-browser",
    "manual/pwa-page-transitions",
    "manual/pwa-each-page-has-url",
    "work-during-interaction",
    "bf-cache",
  ],

  groups: {
    "pwa-installable": {
      title: "Installable",
    },
    "pwa-optimized": {
      title: "PWA Optimized",
    },
    "best-practices-trust-safety": {
      title: "Trust and Safety",
    },
    hidden: {
      title: "",
    },
  },

  categories: {
    "best-practices": {
      title: "Best Practices",
      supportedModes: ["navigation", "timespan", "snapshot"],
      auditRefs: [
        { id: "is-on-https", weight: 5, group: "best-practices-trust-safety" },
      ],
    },
    pwa: {
      title: "PWA",
      description:
        "These checks validate the aspects of a Progressive Web App. [Learn what makes a good Progressive Web App](https://web.dev/pwa-checklist/).",
      manualDescription:
        "These checks are required by the baseline [PWA Checklist](https://web.dev/pwa-checklist/) but are not automatically checked by Lighthouse.",
      supportedModes: ["navigation"],
      auditRefs: [
        { id: "installable-manifest", weight: 2, group: "pwa-installable" },
        { id: "service-worker-audit", weight: 2, group: "pwa-installable" },
        { id: "offline-audit", weight: 1, group: "pwa-installable" },
        { id: "https-audit", weight: 1, group: "pwa-installable" },
      ],
    },
  },
};
export default lighthouseSettings;
