import { LitElement, TemplateResult } from 'lit';
import { Platform } from '../services/publish';
import '@shoelace-style/shoelace/dist/components/button/button.js';
import '@shoelace-style/shoelace/dist/components/dialog/dialog.js';
import './windows-form';
import './android-form';
import './ios-form';
import { PackageOptions } from '../utils/interfaces';
export declare class PublishPane extends LitElement {
    analysisId: string | null;
    generating: boolean;
    cardsOrForm: boolean;
    isGooglePlay: boolean;
    selectedStore: string;
    readyToDownload: boolean;
    blob: Blob | File | null | undefined;
    testBlob: Blob | File | null | undefined;
    downloadFileName: string | null;
    feedbackMessages: TemplateResult[];
    preventClosing: boolean;
    storeMap: any;
    objectStore: string;
    readonly platforms: ICardData[];
    static get styles(): import("lit").CSSResult[];
    constructor();
    firstUpdated(): void;
    renderWindowsDownloadButton(): TemplateResult;
    renderAndroidDownloadButton(): TemplateResult;
    renderiOSDownloadButton(): TemplateResult;
    renderForm(): TemplateResult<1>;
    showWindowsOptions(): void;
    showAndroidOptions(): void;
    toggleApkType(event: any): void;
    showiOSOptions(): void;
    showMetaOptions(): void;
    generate(platform: Platform, options?: PackageOptions): Promise<void>;
    renderErrorMessage(err: any): void;
    renderSuccessMessage(): void;
    copyText(text: string): void;
    downloadPackage(): Promise<void>;
    renderContentCards(): TemplateResult[];
    hideDialog(e: any): Promise<void>;
    handleRequestClose(e: Event): void;
    backToCards(): void;
    renderFormFooter(): TemplateResult<1>;
    submitForm(): void;
    private getFormKey;
    saveFormData(): Promise<void>;
    loadFormData(): Promise<void>;
    updated(changedProps: Map<string, any>): void;
    render(): TemplateResult<1>;
}
interface ICardData {
    title: 'Windows' | 'Android' | 'iOS' | "Meta Quest";
    factoids: string[];
    isActionCard: boolean;
    icon: string;
    renderDownloadButton: () => TemplateResult;
}
export {};
